# Generated by Django 4.0.4 on 2022-05-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_artiles_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'Добавление материалов', 'verbose_name_plural': 'Добавление материалов'},
        ),
    ]
